name: Release

on:
  # push:
  #   branches:
  #     - '*'
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# Add permissions for the GitHub token
permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Install dmg-license (macOS only)
        if: matrix.os == 'macos-latest'
        run: npm install dmg-license --save-dev

      - name: Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ github.event_name == 'push' && github.event.tag_name != '' }}
          build_script_name: ${{ matrix.os == 'macos-latest' && 'build:mac' || matrix.os == 'windows-latest' && 'build:win' || 'build:linux' }}
          skip_build: false
          max_attempts: 3
          args: --config.compression=store